export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RUGOSITE_SUCCESS = "RUGOSITE_SUCCESS";
export const RUGOSITE_FAIL = "RUGOSITE_FAIL";

export const MESURES_SUCCESS = "MESURES_SUCCESS";
export const MESURES_FAIL = "MESURES_FAIL";

export const ORGANISMES_SUCCESS = "ORGANISMES_SUCCESS";
export const ORGANISMES_FAIL = "ORGANISMES_FAIL";

export const UTILISATEUR_SUCCESS = "UTILISATEUR_SUCCESS";
export const UTILISATEUR_FAIL = "UTILISATEUR_FAIL";
